title: AZ-305 Study Notes
description: These are notes taken while studying for AZ-305. Use at your own risk.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
